### ISSUE TITLE
Error when adding field_common_tasks to sub-service landing page

### ISSUE THREAD

**Issue by jhiron-wf** [localgovdrupal/localgov_services#90]
The following error occurred on the service sub-landing page manage form display page after adding the pre-existing field_common_tasks to the content type:

`Notice: Undefined index: name in Drupal\field_ui\Element\FieldUiTable::reduceOrder() (line 228 of core/modules/field_ui/src/Element/FieldUiTable.php)`

Steps to reproduce:
- Add pre-existing field: "field_common_tasks" to service sub-landing page content type
- Go to Manage form display

I looked into the error and found that it was related to the **tabs** field group (https://www.drupal.org/project/field_group/issues/3064890)

After inspecting the form display page and finding that the **tab** field groups were all sat in **Disabled** (also mentioned in the issue linked above), then fiddling around with the layout of the tabs and repositioning them as they should logically be (see below) the error disappeared and has not re-ocurred since:

<img width="1075" alt="Screenshot 2021-02-03 at 19 03 29" src="https://user-images.githubusercontent.com/70009993/106795977-ab2aea80-6652-11eb-939e-63873e08041d.png">

Please let me know if any more clarification or information is needed on this!

**Comment by andybroomfield** [comment]
Thanks for the bug report @jhiron-wf.
This might be two issues, 1st is fixing the obvious bug on the service-sub landing page, and the second is if we should add common tasks by default to sub landing pages.

In terms of the first bug, I think the preinstalled config is malformed.
eg. In the modules config/install directory:
````yaml
    group_topics:
      children:
        - field_topics
      parent_name: group_tabs
      weight: 3
      format_type: tab
      format_settings:
        label: 'Child pages'
        formatter: closed
        description: ''
        required_fields: true
        id: ''
        classes: ''
      label: 'Child pages'
````
And after fixing this by setting up the fields groups as you describe:
````yaml
    group_topics:
      children:
        - field_topics
      parent_name: group_tabs
      weight: 5
      format_type: tab
      format_settings:
        formatter: closed
        description: ''
        required_fields: true
        id: ''
        classes: ''
      label: 'Child pages'
      region: content
````
So I think that's what needs to be changed.

Attached in the exported version of core.entity_form_display.node.localgov_services_sublanding.default.yml
[core.entity_form_display.node.localgov_services_sublanding.default.yml.zip](https://github.com/localgovdrupal/localgov_services/files/5933237/core.entity_form_display.node.localgov_services_sublanding.default.yml.zip)
